spring:
    datasource:
        url: jdbc:mysql://localhost:3306/healthystyle?useSSL=false&serverTimezone=Europe/Warsaw
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: admin
    jpa:
        show-sql: true


    mail:
        host: smtp.gmail.com
        username: businessflowapplication@gmail.com
        password: igfuoabtxcvubuhz
        port: 587
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                    auth: true